/**
 * The Kitchen Codex — Household-Portion Registry (registry-track Phase 5, repair):
 * reviewed initial USDA-derived dataset.
 *
 * PURE, platform-neutral, offline, DETERMINISTIC. DATA ONLY: no matching,
 * ranking, calculation, live-row, analyzer, AI, hydration, Apply, persistence,
 * schema, UI, or server consumer imports this module, and loading it cannot
 * change existing application behavior.
 *
 * VERIFIED-LOADER-ONLY ACCESS
 * ---------------------------
 * Raw record, provenance, and rationale definitions are MODULE-PRIVATE. Nothing
 * is exported except the narrow verified loader (plus fixed identity constants),
 * so a future runtime consumer cannot import unverified grams directly. The
 * loader verifies, in order: the Phase 4 registry lock; the provenance/equivalence
 * contract; the fixed expected provenance digest; and the fixed aggregate release
 * digest that cryptographically commits to both the registry and provenance
 * digests. Any mismatch fails closed and no dataset is exposed.
 *
 * SOURCE AUTHORITY
 * ----------------
 * Every record is derived EXCLUSIVELY from the pinned USDA FoodData Central
 * bundle `usda_fdc_87c5408a3e98838944a87be74824761e`. The pinned canonical record and its declared
 * portion are the numerical authority; no web page, AI value, guess, density,
 * package weight, or bounded estimate is representable.
 *
 * V1 DERIVATION POLICY (reviewed)
 * -------------------------------
 *  - source `amount` and `gram_weight` must BOTH be declared and positive;
 *  - the source portion amount must equal EXACTLY `1`, so
 *    `grams_per_unit === gram_weight` by construction (non-one amounts require
 *    a future reviewed rational/decimal derivation contract);
 *  - a size-only whole-food portion maps to `household_unit: 'item'` with the
 *    declared canonical size; no source diameter/size evidence is dropped from a
 *    record that would need it (which is why the onion/lime generic-item
 *    candidates were rejected rather than reclassified);
 *  - `usda_fdc_ids` lists the derivation source first and may add additional
 *    eligible FDCs of the same ordinary food identity only with a positive,
 *    reviewable equivalence rationale for every pairing.
 *
 * EXTERNAL LOCK
 * -------------
 * `initialLock.ts` is the reviewed separate-module source-controlled lock. It
 * pins the registry lock, the provenance digest, and the aggregate release
 * digest. It is not an external signature or distribution trust service: no
 * external cryptographic trust anchor exists yet.
 */

import {
  HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
  type HouseholdPortionRecordInput,
} from './types';
import { loadHouseholdPortionRegistry, type HouseholdPortionRegistry } from './registry';
import {
  HOUSEHOLD_INITIAL_AGGREGATE_RELEASE_DIGEST,
  HOUSEHOLD_INITIAL_PROVENANCE_DIGEST,
  HOUSEHOLD_INITIAL_REGISTRY_LOCK,
  HOUSEHOLD_INITIAL_REGISTRY_RELEASE,
} from './initialLock';
import {
  computeHouseholdInitialAggregateDigest,
  computeHouseholdInitialProvenanceDigest,
  validateHouseholdInitialProvenance,
  type HouseholdPortionEquivalenceRationale,
  type HouseholdPortionInitialProvenance,
} from './initialProvenance';

/** Pinned USDA bundle every initial record is derived from. */
export const HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE = 'usda_fdc_87c5408a3e98838944a87be74824761e';

/** Fixed review date for this curated slice (never a clock read). */
export const HOUSEHOLD_INITIAL_REVIEWED_AT = '2026-09-24';

/** Closed Phase 5 failure taxonomy (fixed, bounded, input-redacted messages). */
export type HouseholdInitialFailureCode =
  | 'initial_registry_rejected'
  | 'initial_provenance_invalid'
  | 'initial_provenance_digest_mismatch'
  | 'initial_aggregate_digest_mismatch';

export interface HouseholdInitialFailure {
  readonly code: HouseholdInitialFailureCode;
  readonly message: string;
}

const INITIAL_FAILURE_MESSAGE: Readonly<Record<HouseholdInitialFailureCode, string>> = Object.freeze({
  initial_registry_rejected: 'household_initial_registry_rejected',
  initial_provenance_invalid: 'household_initial_provenance_invalid',
  initial_provenance_digest_mismatch: 'household_initial_provenance_digest_mismatch',
  initial_aggregate_digest_mismatch: 'household_initial_aggregate_digest_mismatch',
});

function initialFailure(code: HouseholdInitialFailureCode): { ok: false; failure: HouseholdInitialFailure } {
  return { ok: false, failure: { code, message: INITIAL_FAILURE_MESSAGE[code] } };
}

/** Immutable verified dataset returned only by the lock-verifying loader. */
export interface HouseholdInitialVerifiedDataset {
  readonly schema_version: typeof HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION;
  readonly registry_release: string;
  readonly source_bundle_release: string;
  readonly reviewed_at: string;
  readonly record_count: number;
  readonly registry_digest: string;
  readonly provenance_digest: string;
  readonly aggregate_release_digest: string;
  provenance(): ReadonlyArray<HouseholdPortionInitialProvenance>;
  equivalence(): ReadonlyArray<HouseholdPortionEquivalenceRationale>;
}

export type HouseholdInitialLoadResult =
  | { ok: true; registry: HouseholdPortionRegistry; dataset: HouseholdInitialVerifiedDataset }
  | { ok: false; failure: HouseholdInitialFailure };

// ---------------------------------------------------------------------------
// MODULE-PRIVATE authored data (never exported; frozen)
// ---------------------------------------------------------------------------

const RECORDS: ReadonlyArray<HouseholdPortionRecordInput> = Object.freeze([
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "garlic",
    aliases: [],
    usda_fdc_ids: [169230, 2709786],
    household_unit: "clove",
    size_class: null,
    grams_per_unit: 3,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169230 Garlic, raw; portion 84480 (1 x clove = 3 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "tomato",
    aliases: [],
    usda_fdc_ids: [170457, 2709719],
    household_unit: "item",
    size_class: "small",
    grams_per_unit: 91,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 170457 Tomatoes, red, ripe, raw, year round average; portion 86689 (1 x small whole (2-2/5\" dia) = 91 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "tomato",
    aliases: [],
    usda_fdc_ids: [170457, 2709719],
    household_unit: "item",
    size_class: "medium",
    grams_per_unit: 123,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 170457 Tomatoes, red, ripe, raw, year round average; portion 86686 (1 x medium whole (2-3/5\" dia) = 123 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "tomato",
    aliases: [],
    usda_fdc_ids: [170457, 2709719],
    household_unit: "item",
    size_class: "large",
    grams_per_unit: 182,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 170457 Tomatoes, red, ripe, raw, year round average; portion 86685 (1 x large whole (3\" dia) = 182 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "green bell pepper",
    aliases: [],
    usda_fdc_ids: [170427, 2258588],
    household_unit: "item",
    size_class: "small",
    grams_per_unit: 74,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 170427 Peppers, sweet, green, raw; portion 86629 (1 x small = 74 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "green bell pepper",
    aliases: [],
    usda_fdc_ids: [170427, 2258588],
    household_unit: "item",
    size_class: "medium",
    grams_per_unit: 119,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 170427 Peppers, sweet, green, raw; portion 86627 (1 x medium (approx 2-3/4\" long, 2-1/2\" dia) = 119 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "green bell pepper",
    aliases: [],
    usda_fdc_ids: [170427, 2258588],
    household_unit: "item",
    size_class: "large",
    grams_per_unit: 164,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 170427 Peppers, sweet, green, raw; portion 86626 (1 x large (2-1/4 per lb, approx 3-3/4\" long, 3\" dia) = 164 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "red bell pepper",
    aliases: [],
    usda_fdc_ids: [170108, 2258590],
    household_unit: "item",
    size_class: "small",
    grams_per_unit: 74,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 170108 Peppers, sweet, red, raw; portion 86067 (1 x small = 74 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "red bell pepper",
    aliases: [],
    usda_fdc_ids: [170108, 2258590],
    household_unit: "item",
    size_class: "medium",
    grams_per_unit: 119,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 170108 Peppers, sweet, red, raw; portion 86066 (1 x medium (approx 2-3/4\" long, 2-1/2 dia.) = 119 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "red bell pepper",
    aliases: [],
    usda_fdc_ids: [170108, 2258590],
    household_unit: "item",
    size_class: "large",
    grams_per_unit: 164,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 170108 Peppers, sweet, red, raw; portion 86065 (1 x large (2-1/4 per pound, approx 3-3/4\" long, 3\" dia.) = 164 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "green cabbage",
    aliases: [],
    usda_fdc_ids: [169975, 2346407],
    household_unit: "head",
    size_class: "small",
    grams_per_unit: 714,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169975 Cabbage, raw; portion 85797 (1 x head, small (about 4-1/2\" dia) = 714 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "green cabbage",
    aliases: [],
    usda_fdc_ids: [169975, 2346407],
    household_unit: "head",
    size_class: "medium",
    grams_per_unit: 908,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169975 Cabbage, raw; portion 85795 (1 x head, medium (about 5-3/4\" dia) = 908 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "green cabbage",
    aliases: [],
    usda_fdc_ids: [169975, 2346407],
    household_unit: "head",
    size_class: "large",
    grams_per_unit: 1248,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169975 Cabbage, raw; portion 85793 (1 x head, large (about 7\" dia) = 1248 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "red cabbage",
    aliases: [],
    usda_fdc_ids: [169977, 2346408],
    household_unit: "head",
    size_class: "small",
    grams_per_unit: 567,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169977 Cabbage, red, raw; portion 85806 (1 x head, small (4\" dia) = 567 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "red cabbage",
    aliases: [],
    usda_fdc_ids: [169977, 2346408],
    household_unit: "head",
    size_class: "medium",
    grams_per_unit: 839,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169977 Cabbage, red, raw; portion 85805 (1 x head, medium (about 5\" dia) = 839 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "red cabbage",
    aliases: [],
    usda_fdc_ids: [169977, 2346408],
    household_unit: "head",
    size_class: "large",
    grams_per_unit: 1134,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169977 Cabbage, red, raw; portion 85803 (1 x head, large (about 5-1/2\" dia) = 1134 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "egg",
    aliases: [],
    usda_fdc_ids: [171287],
    household_unit: "item",
    size_class: "small",
    grams_per_unit: 38,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 171287 Egg, whole, raw, fresh; portion 88379 (1 x small = 38 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "egg",
    aliases: [],
    usda_fdc_ids: [171287],
    household_unit: "item",
    size_class: "medium",
    grams_per_unit: 44,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 171287 Egg, whole, raw, fresh; portion 88378 (1 x medium = 44 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "egg",
    aliases: [],
    usda_fdc_ids: [171287],
    household_unit: "item",
    size_class: "large",
    grams_per_unit: 50,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 171287 Egg, whole, raw, fresh; portion 88374 (1 x large = 50 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "egg",
    aliases: [],
    usda_fdc_ids: [171287],
    household_unit: "item",
    size_class: "xl",
    grams_per_unit: 56,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 171287 Egg, whole, raw, fresh; portion 88375 (1 x extra large = 56 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "egg",
    aliases: [],
    usda_fdc_ids: [171287],
    household_unit: "item",
    size_class: "jumbo",
    grams_per_unit: 63,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 171287 Egg, whole, raw, fresh; portion 88376 (1 x jumbo = 63 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "unsalted butter",
    aliases: [],
    usda_fdc_ids: [173430, 789828],
    household_unit: "stick",
    size_class: null,
    grams_per_unit: 113,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 173430 Butter, without salt; portion 92514 (1 x stick = 113 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "white mushroom",
    aliases: [],
    usda_fdc_ids: [169251, 2709793],
    household_unit: "item",
    size_class: "small",
    grams_per_unit: 10,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169251 Mushrooms, white, raw; portion 84531 (1 x small = 10 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "white mushroom",
    aliases: [],
    usda_fdc_ids: [169251, 2709793],
    household_unit: "item",
    size_class: "medium",
    grams_per_unit: 18,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169251 Mushrooms, white, raw; portion 84529 (1 x medium = 18 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "white mushroom",
    aliases: [],
    usda_fdc_ids: [169251, 2709793],
    household_unit: "item",
    size_class: "large",
    grams_per_unit: 23,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169251 Mushrooms, white, raw; portion 84528 (1 x large = 23 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "peach",
    aliases: [],
    usda_fdc_ids: [169928, 2709249],
    household_unit: "item",
    size_class: "small",
    grams_per_unit: 130,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169928 Peaches, yellow, raw; portion 85698 (1 x small (2-1/2\" dia) = 130 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "peach",
    aliases: [],
    usda_fdc_ids: [169928, 2709249],
    household_unit: "item",
    size_class: "medium",
    grams_per_unit: 150,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169928 Peaches, yellow, raw; portion 85699 (1 x medium (2-2/3\" dia) = 150 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "peach",
    aliases: [],
    usda_fdc_ids: [169928, 2709249],
    household_unit: "item",
    size_class: "large",
    grams_per_unit: 175,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169928 Peaches, yellow, raw; portion 85700 (1 x large (2-3/4\" dia) = 175 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "zucchini",
    aliases: [],
    usda_fdc_ids: [169291],
    household_unit: "item",
    size_class: "small",
    grams_per_unit: 118,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169291 Squash, summer, zucchini, includes skin, raw; portion 84612 (1 x small = 118 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "zucchini",
    aliases: [],
    usda_fdc_ids: [169291],
    household_unit: "item",
    size_class: "medium",
    grams_per_unit: 196,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169291 Squash, summer, zucchini, includes skin, raw; portion 84610 (1 x medium = 196 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
  {
    schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
    food_key: "zucchini",
    aliases: [],
    usda_fdc_ids: [169291],
    household_unit: "item",
    size_class: "large",
    grams_per_unit: 323,
    quantity_behavior: 'linear',
    requires_state: null,
    excluded_states: [],
    exclude_generic_identity: false,
    authority_class: 'usda_derived',
    bounds: null,
    source: {
      kind: 'usda_fdc',
      citation: "USDA FDC 169291 Squash, summer, zucchini, includes skin, raw; portion 84609 (1 x large = 323 g); bundle usda_fdc_87c5408a3e98838944a87be74824761e",
      url: null,
      accessed: null,
    },
    reviewed_at: "2026-09-24",
    supersedes: null,
  },
]);

const PROVENANCE: ReadonlyArray<HouseholdPortionInitialProvenance> = Object.freeze([
  {
    record_key: "garlic|clove|null|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169230,
    source_record_digest: "d19a0c659ab0a98218bf1eb3f8463ddfc3fc243185fa8b185cf6e204f0aeb199",
    source_portion_index: 1,
    source_portion_id: "84480",
    portion_amount: 1,
    portion_gram_weight: 3,
    portion_measure: "undetermined",
    portion_modifier: "clove",
    derived_grams_per_unit: 3,
    citation_fdc_id: 169230,
    citation_portion_id: "84480",
  },
  {
    record_key: "tomato|item|small|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 170457,
    source_record_digest: "cf546a5cceefb502b3568b3c1501af43a6b5fcb685c6a73f2fd52d1e83eda245",
    source_portion_index: 7,
    source_portion_id: "86689",
    portion_amount: 1,
    portion_gram_weight: 91,
    portion_measure: "undetermined",
    portion_modifier: "small whole (2-2/5\" dia)",
    derived_grams_per_unit: 91,
    citation_fdc_id: 170457,
    citation_portion_id: "86689",
  },
  {
    record_key: "tomato|item|medium|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 170457,
    source_record_digest: "cf546a5cceefb502b3568b3c1501af43a6b5fcb685c6a73f2fd52d1e83eda245",
    source_portion_index: 0,
    source_portion_id: "86686",
    portion_amount: 1,
    portion_gram_weight: 123,
    portion_measure: "undetermined",
    portion_modifier: "medium whole (2-3/5\" dia)",
    derived_grams_per_unit: 123,
    citation_fdc_id: 170457,
    citation_portion_id: "86686",
  },
  {
    record_key: "tomato|item|large|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 170457,
    source_record_digest: "cf546a5cceefb502b3568b3c1501af43a6b5fcb685c6a73f2fd52d1e83eda245",
    source_portion_index: 2,
    source_portion_id: "86685",
    portion_amount: 1,
    portion_gram_weight: 182,
    portion_measure: "undetermined",
    portion_modifier: "large whole (3\" dia)",
    derived_grams_per_unit: 182,
    citation_fdc_id: 170457,
    citation_portion_id: "86685",
  },
  {
    record_key: "green bell pepper|item|small|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 170427,
    source_record_digest: "695758e21ea2e6c1efd887b93b20c9733c788f9d1d31d72b01a9b2afa529008a",
    source_portion_index: 6,
    source_portion_id: "86629",
    portion_amount: 1,
    portion_gram_weight: 74,
    portion_measure: "undetermined",
    portion_modifier: "small",
    derived_grams_per_unit: 74,
    citation_fdc_id: 170427,
    citation_portion_id: "86629",
  },
  {
    record_key: "green bell pepper|item|medium|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 170427,
    source_record_digest: "695758e21ea2e6c1efd887b93b20c9733c788f9d1d31d72b01a9b2afa529008a",
    source_portion_index: 5,
    source_portion_id: "86627",
    portion_amount: 1,
    portion_gram_weight: 119,
    portion_measure: "undetermined",
    portion_modifier: "medium (approx 2-3/4\" long, 2-1/2\" dia)",
    derived_grams_per_unit: 119,
    citation_fdc_id: 170427,
    citation_portion_id: "86627",
  },
  {
    record_key: "green bell pepper|item|large|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 170427,
    source_record_digest: "695758e21ea2e6c1efd887b93b20c9733c788f9d1d31d72b01a9b2afa529008a",
    source_portion_index: 4,
    source_portion_id: "86626",
    portion_amount: 1,
    portion_gram_weight: 164,
    portion_measure: "undetermined",
    portion_modifier: "large (2-1/4 per lb, approx 3-3/4\" long, 3\" dia)",
    derived_grams_per_unit: 164,
    citation_fdc_id: 170427,
    citation_portion_id: "86626",
  },
  {
    record_key: "red bell pepper|item|small|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 170108,
    source_record_digest: "cb9e311a60eaeeeff04f85a6c7fee260d01d72734825b00c5232e3bb6357c3e7",
    source_portion_index: 6,
    source_portion_id: "86067",
    portion_amount: 1,
    portion_gram_weight: 74,
    portion_measure: "undetermined",
    portion_modifier: "small",
    derived_grams_per_unit: 74,
    citation_fdc_id: 170108,
    citation_portion_id: "86067",
  },
  {
    record_key: "red bell pepper|item|medium|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 170108,
    source_record_digest: "cb9e311a60eaeeeff04f85a6c7fee260d01d72734825b00c5232e3bb6357c3e7",
    source_portion_index: 5,
    source_portion_id: "86066",
    portion_amount: 1,
    portion_gram_weight: 119,
    portion_measure: "undetermined",
    portion_modifier: "medium (approx 2-3/4\" long, 2-1/2 dia.)",
    derived_grams_per_unit: 119,
    citation_fdc_id: 170108,
    citation_portion_id: "86066",
  },
  {
    record_key: "red bell pepper|item|large|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 170108,
    source_record_digest: "cb9e311a60eaeeeff04f85a6c7fee260d01d72734825b00c5232e3bb6357c3e7",
    source_portion_index: 0,
    source_portion_id: "86065",
    portion_amount: 1,
    portion_gram_weight: 164,
    portion_measure: "undetermined",
    portion_modifier: "large (2-1/4 per pound, approx 3-3/4\" long, 3\" dia.)",
    derived_grams_per_unit: 164,
    citation_fdc_id: 170108,
    citation_portion_id: "86065",
  },
  {
    record_key: "green cabbage|head|small|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169975,
    source_record_digest: "9aa263ec13d7f6c0db8410c871a6bb3014990455ead4b6889181dac5d2c8168c",
    source_portion_index: 7,
    source_portion_id: "85797",
    portion_amount: 1,
    portion_gram_weight: 714,
    portion_measure: "undetermined",
    portion_modifier: "head, small (about 4-1/2\" dia)",
    derived_grams_per_unit: 714,
    citation_fdc_id: 169975,
    citation_portion_id: "85797",
  },
  {
    record_key: "green cabbage|head|medium|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169975,
    source_record_digest: "9aa263ec13d7f6c0db8410c871a6bb3014990455ead4b6889181dac5d2c8168c",
    source_portion_index: 1,
    source_portion_id: "85795",
    portion_amount: 1,
    portion_gram_weight: 908,
    portion_measure: "undetermined",
    portion_modifier: "head, medium (about 5-3/4\" dia)",
    derived_grams_per_unit: 908,
    citation_fdc_id: 169975,
    citation_portion_id: "85795",
  },
  {
    record_key: "green cabbage|head|large|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169975,
    source_record_digest: "9aa263ec13d7f6c0db8410c871a6bb3014990455ead4b6889181dac5d2c8168c",
    source_portion_index: 6,
    source_portion_id: "85793",
    portion_amount: 1,
    portion_gram_weight: 1248,
    portion_measure: "undetermined",
    portion_modifier: "head, large (about 7\" dia)",
    derived_grams_per_unit: 1248,
    citation_fdc_id: 169975,
    citation_portion_id: "85793",
  },
  {
    record_key: "red cabbage|head|small|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169977,
    source_record_digest: "1bec782fe84e735291caa4a90b7f43da9e66542b0ca573c0e6fbcebef7a95088",
    source_portion_index: 5,
    source_portion_id: "85806",
    portion_amount: 1,
    portion_gram_weight: 567,
    portion_measure: "undetermined",
    portion_modifier: "head, small (4\" dia)",
    derived_grams_per_unit: 567,
    citation_fdc_id: 169977,
    citation_portion_id: "85806",
  },
  {
    record_key: "red cabbage|head|medium|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169977,
    source_record_digest: "1bec782fe84e735291caa4a90b7f43da9e66542b0ca573c0e6fbcebef7a95088",
    source_portion_index: 3,
    source_portion_id: "85805",
    portion_amount: 1,
    portion_gram_weight: 839,
    portion_measure: "undetermined",
    portion_modifier: "head, medium (about 5\" dia)",
    derived_grams_per_unit: 839,
    citation_fdc_id: 169977,
    citation_portion_id: "85805",
  },
  {
    record_key: "red cabbage|head|large|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169977,
    source_record_digest: "1bec782fe84e735291caa4a90b7f43da9e66542b0ca573c0e6fbcebef7a95088",
    source_portion_index: 4,
    source_portion_id: "85803",
    portion_amount: 1,
    portion_gram_weight: 1134,
    portion_measure: "undetermined",
    portion_modifier: "head, large (about 5-1/2\" dia)",
    derived_grams_per_unit: 1134,
    citation_fdc_id: 169977,
    citation_portion_id: "85803",
  },
  {
    record_key: "egg|item|small|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 171287,
    source_record_digest: "a0e54be923de4bdf47859457e203fddd2acc23ba797659aba2256d56dc4d0d90",
    source_portion_index: 3,
    source_portion_id: "88379",
    portion_amount: 1,
    portion_gram_weight: 38,
    portion_measure: "undetermined",
    portion_modifier: "small",
    derived_grams_per_unit: 38,
    citation_fdc_id: 171287,
    citation_portion_id: "88379",
  },
  {
    record_key: "egg|item|medium|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 171287,
    source_record_digest: "a0e54be923de4bdf47859457e203fddd2acc23ba797659aba2256d56dc4d0d90",
    source_portion_index: 1,
    source_portion_id: "88378",
    portion_amount: 1,
    portion_gram_weight: 44,
    portion_measure: "undetermined",
    portion_modifier: "medium",
    derived_grams_per_unit: 44,
    citation_fdc_id: 171287,
    citation_portion_id: "88378",
  },
  {
    record_key: "egg|item|large|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 171287,
    source_record_digest: "a0e54be923de4bdf47859457e203fddd2acc23ba797659aba2256d56dc4d0d90",
    source_portion_index: 5,
    source_portion_id: "88374",
    portion_amount: 1,
    portion_gram_weight: 50,
    portion_measure: "undetermined",
    portion_modifier: "large",
    derived_grams_per_unit: 50,
    citation_fdc_id: 171287,
    citation_portion_id: "88374",
  },
  {
    record_key: "egg|item|xl|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 171287,
    source_record_digest: "a0e54be923de4bdf47859457e203fddd2acc23ba797659aba2256d56dc4d0d90",
    source_portion_index: 2,
    source_portion_id: "88375",
    portion_amount: 1,
    portion_gram_weight: 56,
    portion_measure: "undetermined",
    portion_modifier: "extra large",
    derived_grams_per_unit: 56,
    citation_fdc_id: 171287,
    citation_portion_id: "88375",
  },
  {
    record_key: "egg|item|jumbo|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 171287,
    source_record_digest: "a0e54be923de4bdf47859457e203fddd2acc23ba797659aba2256d56dc4d0d90",
    source_portion_index: 4,
    source_portion_id: "88376",
    portion_amount: 1,
    portion_gram_weight: 63,
    portion_measure: "undetermined",
    portion_modifier: "jumbo",
    derived_grams_per_unit: 63,
    citation_fdc_id: 171287,
    citation_portion_id: "88376",
  },
  {
    record_key: "unsalted butter|stick|null|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 173430,
    source_record_digest: "c0caa07bb704557cab0f0bc65fcabb6e6d3a41a5cb2bef989c2c470d3f7c01a3",
    source_portion_index: 2,
    source_portion_id: "92514",
    portion_amount: 1,
    portion_gram_weight: 113,
    portion_measure: "undetermined",
    portion_modifier: "stick",
    derived_grams_per_unit: 113,
    citation_fdc_id: 173430,
    citation_portion_id: "92514",
  },
  {
    record_key: "white mushroom|item|small|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169251,
    source_record_digest: "24ef4b69d1091c3a2ea31b308f3f457a5680acb2f44fe3413af085d38eaf591c",
    source_portion_index: 0,
    source_portion_id: "84531",
    portion_amount: 1,
    portion_gram_weight: 10,
    portion_measure: "undetermined",
    portion_modifier: "small",
    derived_grams_per_unit: 10,
    citation_fdc_id: 169251,
    citation_portion_id: "84531",
  },
  {
    record_key: "white mushroom|item|medium|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169251,
    source_record_digest: "24ef4b69d1091c3a2ea31b308f3f457a5680acb2f44fe3413af085d38eaf591c",
    source_portion_index: 4,
    source_portion_id: "84529",
    portion_amount: 1,
    portion_gram_weight: 18,
    portion_measure: "undetermined",
    portion_modifier: "medium",
    derived_grams_per_unit: 18,
    citation_fdc_id: 169251,
    citation_portion_id: "84529",
  },
  {
    record_key: "white mushroom|item|large|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169251,
    source_record_digest: "24ef4b69d1091c3a2ea31b308f3f457a5680acb2f44fe3413af085d38eaf591c",
    source_portion_index: 5,
    source_portion_id: "84528",
    portion_amount: 1,
    portion_gram_weight: 23,
    portion_measure: "undetermined",
    portion_modifier: "large",
    derived_grams_per_unit: 23,
    citation_fdc_id: 169251,
    citation_portion_id: "84528",
  },
  {
    record_key: "peach|item|small|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169928,
    source_record_digest: "b2114975b3c25736e64ec25d8aa369aa72c745073a6373553e08a218f8631a6c",
    source_portion_index: 0,
    source_portion_id: "85698",
    portion_amount: 1,
    portion_gram_weight: 130,
    portion_measure: "undetermined",
    portion_modifier: "small (2-1/2\" dia)",
    derived_grams_per_unit: 130,
    citation_fdc_id: 169928,
    citation_portion_id: "85698",
  },
  {
    record_key: "peach|item|medium|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169928,
    source_record_digest: "b2114975b3c25736e64ec25d8aa369aa72c745073a6373553e08a218f8631a6c",
    source_portion_index: 3,
    source_portion_id: "85699",
    portion_amount: 1,
    portion_gram_weight: 150,
    portion_measure: "undetermined",
    portion_modifier: "medium (2-2/3\" dia)",
    derived_grams_per_unit: 150,
    citation_fdc_id: 169928,
    citation_portion_id: "85699",
  },
  {
    record_key: "peach|item|large|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169928,
    source_record_digest: "b2114975b3c25736e64ec25d8aa369aa72c745073a6373553e08a218f8631a6c",
    source_portion_index: 2,
    source_portion_id: "85700",
    portion_amount: 1,
    portion_gram_weight: 175,
    portion_measure: "undetermined",
    portion_modifier: "large (2-3/4\" dia)",
    derived_grams_per_unit: 175,
    citation_fdc_id: 169928,
    citation_portion_id: "85700",
  },
  {
    record_key: "zucchini|item|small|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169291,
    source_record_digest: "f381cd6af3912a428ee6dae620f133246cadb78b644648c55ded77d459fcd9b7",
    source_portion_index: 3,
    source_portion_id: "84612",
    portion_amount: 1,
    portion_gram_weight: 118,
    portion_measure: "undetermined",
    portion_modifier: "small",
    derived_grams_per_unit: 118,
    citation_fdc_id: 169291,
    citation_portion_id: "84612",
  },
  {
    record_key: "zucchini|item|medium|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169291,
    source_record_digest: "f381cd6af3912a428ee6dae620f133246cadb78b644648c55ded77d459fcd9b7",
    source_portion_index: 1,
    source_portion_id: "84610",
    portion_amount: 1,
    portion_gram_weight: 196,
    portion_measure: "undetermined",
    portion_modifier: "medium",
    derived_grams_per_unit: 196,
    citation_fdc_id: 169291,
    citation_portion_id: "84610",
  },
  {
    record_key: "zucchini|item|large|null",
    source_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
    source_fdc_id: 169291,
    source_record_digest: "f381cd6af3912a428ee6dae620f133246cadb78b644648c55ded77d459fcd9b7",
    source_portion_index: 0,
    source_portion_id: "84609",
    portion_amount: 1,
    portion_gram_weight: 323,
    portion_measure: "undetermined",
    portion_modifier: "large",
    derived_grams_per_unit: 323,
    citation_fdc_id: 169291,
    citation_portion_id: "84609",
  },
].map((entry) => Object.freeze(entry as HouseholdPortionInitialProvenance)));

const EQUIVALENCE: ReadonlyArray<HouseholdPortionEquivalenceRationale> = Object.freeze([
  {
    record_key: "garlic|clove|null|null",
    source_fdc_id: 169230,
    source_description: "Garlic, raw",
    bound_fdc_id: 2709786,
    bound_description: "Garlic, raw",
    species_family: "Allium sativum (garlic), bulb; peeled clove as the counted item",
    state: "raw in both records",
    color_variety: "common garlic; neither description declares a color or named variety",
    edible_form: "edible peeled clove",
    positive_evidence: "Both records carry the identical description \"Garlic, raw\" and each declares a clove-shaped portion: SR Legacy 1 clove = 3 g and 3 cloves = 9 g (an identical 3 g per-clove relationship), and FNDDS declares a clove-shaped portion at exactly 3 g.",
    corroborating_portion: "FNDDS 2709786 measure \"1 clove\" reports 3 g (amount omitted), matching the SR per-clove value exactly; the amount-less FNDDS portion is a gram match only, not an independent amount-bearing conversion.",
    data_type_difference: "SR Legacy food-composition record vs FNDDS survey-grouping record; the FNDDS category \"Mustard and other condiments\" is a survey-grouping artifact, not a different food.",
    nutrient_profile_delta: "Per-100-g: SR 149 kcal / 33.1 g carbs / 2.1 g fiber vs FNDDS 143 kcal / 28.2 g carbs / 2.7 g fiber; nutrients are never transferred.",
    conclusion: "Positive species/state/edible-form equivalence plus an exact clove-shaped gram match permits transfer of the household clove mass relationship only; no nutrient or identity authority transfers.",
  },
  {
    record_key: "tomato|item|small|null",
    source_fdc_id: 170457,
    source_description: "Tomatoes, red, ripe, raw, year round average",
    bound_fdc_id: 2709719,
    bound_description: "Tomatoes, raw",
    species_family: "Solanum lycopersicum (tomato), red ripe",
    state: "raw in both records",
    color_variety: "red ripe tomato; the bound FNDDS record is the plain raw-tomato identity",
    edible_form: "whole tomato; the SR record also exposes authenticated slice/wedge forms",
    positive_evidence: "Both records describe the plain raw tomato, and the bound FNDDS record declares its own whole-tomato portion (\"1 whole\"), so the whole-item form is positively present on both sides.",
    corroborating_portion: "FNDDS 2709719 \"1 whole\" reports 125 g (amount omitted), corroborating the whole-tomato item shape; the SR sized values 91/123/182 g are the authenticated size-class conversions.",
    data_type_difference: "SR Legacy year-round-average composition record vs FNDDS survey record; FNDDS may blend varieties under one plain tomato identity.",
    nutrient_profile_delta: "Per-100-g: SR 18 kcal / 3.89 g carbs vs FNDDS 20 kcal / 4.04 g carbs; nutrients are never transferred.",
    conclusion: "Positive species/state/whole-form equivalence permits transfer of the item size-class mass relationships only; the FNDDS whole value is never averaged into or treated as a size class.",
  },
  {
    record_key: "tomato|item|medium|null",
    source_fdc_id: 170457,
    source_description: "Tomatoes, red, ripe, raw, year round average",
    bound_fdc_id: 2709719,
    bound_description: "Tomatoes, raw",
    species_family: "Solanum lycopersicum (tomato), red ripe",
    state: "raw in both records",
    color_variety: "red ripe tomato; the bound FNDDS record is the plain raw-tomato identity",
    edible_form: "whole tomato; the SR record also exposes authenticated slice/wedge forms",
    positive_evidence: "Both records describe the plain raw tomato, and the bound FNDDS record declares its own whole-tomato portion (\"1 whole\"), so the whole-item form is positively present on both sides.",
    corroborating_portion: "FNDDS 2709719 \"1 whole\" reports 125 g (amount omitted), corroborating the whole-tomato item shape; the SR sized values 91/123/182 g are the authenticated size-class conversions.",
    data_type_difference: "SR Legacy year-round-average composition record vs FNDDS survey record; FNDDS may blend varieties under one plain tomato identity.",
    nutrient_profile_delta: "Per-100-g: SR 18 kcal / 3.89 g carbs vs FNDDS 20 kcal / 4.04 g carbs; nutrients are never transferred.",
    conclusion: "Positive species/state/whole-form equivalence permits transfer of the item size-class mass relationships only; the FNDDS whole value is never averaged into or treated as a size class.",
  },
  {
    record_key: "tomato|item|large|null",
    source_fdc_id: 170457,
    source_description: "Tomatoes, red, ripe, raw, year round average",
    bound_fdc_id: 2709719,
    bound_description: "Tomatoes, raw",
    species_family: "Solanum lycopersicum (tomato), red ripe",
    state: "raw in both records",
    color_variety: "red ripe tomato; the bound FNDDS record is the plain raw-tomato identity",
    edible_form: "whole tomato; the SR record also exposes authenticated slice/wedge forms",
    positive_evidence: "Both records describe the plain raw tomato, and the bound FNDDS record declares its own whole-tomato portion (\"1 whole\"), so the whole-item form is positively present on both sides.",
    corroborating_portion: "FNDDS 2709719 \"1 whole\" reports 125 g (amount omitted), corroborating the whole-tomato item shape; the SR sized values 91/123/182 g are the authenticated size-class conversions.",
    data_type_difference: "SR Legacy year-round-average composition record vs FNDDS survey record; FNDDS may blend varieties under one plain tomato identity.",
    nutrient_profile_delta: "Per-100-g: SR 18 kcal / 3.89 g carbs vs FNDDS 20 kcal / 4.04 g carbs; nutrients are never transferred.",
    conclusion: "Positive species/state/whole-form equivalence permits transfer of the item size-class mass relationships only; the FNDDS whole value is never averaged into or treated as a size class.",
  },
  {
    record_key: "green bell pepper|item|small|null",
    source_fdc_id: 170427,
    source_description: "Peppers, sweet, green, raw",
    bound_fdc_id: 2258588,
    bound_description: "Peppers, bell, green, raw",
    species_family: "Capsicum annuum (bell/sweet pepper), green",
    state: "raw in both records",
    color_variety: "green; USDA uses \"sweet\" and \"bell\" for the same green pepper",
    edible_form: "whole pepper; the SR record also exposes strips/rings",
    positive_evidence: "The bound Foundation record \"Peppers, bell, green, raw\" and the SR record \"Peppers, sweet, green, raw\" name the same green pepper food: both are raw, both are green, and both describe the whole-pepper item.",
    corroborating_portion: "The bound Foundation record declares a RACC reference amount (85 g) and no household size class; the SR record supplies the authenticated small/medium/large item masses.",
    data_type_difference: "SR Legacy composition record vs Foundation modern analytical record for the same food.",
    nutrient_profile_delta: "Per-100-g: SR 20 kcal / 4.64 g carbs / 1.7 g fiber vs Foundation 4.78 g carbs / 0.942 g fiber (kcal absent); nutrients are never transferred.",
    conclusion: "Positive species/color/state/whole-form equivalence permits transfer of the whole-pepper size masses only; the RACC reference amount is not a household conversion and is never used.",
  },
  {
    record_key: "green bell pepper|item|medium|null",
    source_fdc_id: 170427,
    source_description: "Peppers, sweet, green, raw",
    bound_fdc_id: 2258588,
    bound_description: "Peppers, bell, green, raw",
    species_family: "Capsicum annuum (bell/sweet pepper), green",
    state: "raw in both records",
    color_variety: "green; USDA uses \"sweet\" and \"bell\" for the same green pepper",
    edible_form: "whole pepper; the SR record also exposes strips/rings",
    positive_evidence: "The bound Foundation record \"Peppers, bell, green, raw\" and the SR record \"Peppers, sweet, green, raw\" name the same green pepper food: both are raw, both are green, and both describe the whole-pepper item.",
    corroborating_portion: "The bound Foundation record declares a RACC reference amount (85 g) and no household size class; the SR record supplies the authenticated small/medium/large item masses.",
    data_type_difference: "SR Legacy composition record vs Foundation modern analytical record for the same food.",
    nutrient_profile_delta: "Per-100-g: SR 20 kcal / 4.64 g carbs / 1.7 g fiber vs Foundation 4.78 g carbs / 0.942 g fiber (kcal absent); nutrients are never transferred.",
    conclusion: "Positive species/color/state/whole-form equivalence permits transfer of the whole-pepper size masses only; the RACC reference amount is not a household conversion and is never used.",
  },
  {
    record_key: "green bell pepper|item|large|null",
    source_fdc_id: 170427,
    source_description: "Peppers, sweet, green, raw",
    bound_fdc_id: 2258588,
    bound_description: "Peppers, bell, green, raw",
    species_family: "Capsicum annuum (bell/sweet pepper), green",
    state: "raw in both records",
    color_variety: "green; USDA uses \"sweet\" and \"bell\" for the same green pepper",
    edible_form: "whole pepper; the SR record also exposes strips/rings",
    positive_evidence: "The bound Foundation record \"Peppers, bell, green, raw\" and the SR record \"Peppers, sweet, green, raw\" name the same green pepper food: both are raw, both are green, and both describe the whole-pepper item.",
    corroborating_portion: "The bound Foundation record declares a RACC reference amount (85 g) and no household size class; the SR record supplies the authenticated small/medium/large item masses.",
    data_type_difference: "SR Legacy composition record vs Foundation modern analytical record for the same food.",
    nutrient_profile_delta: "Per-100-g: SR 20 kcal / 4.64 g carbs / 1.7 g fiber vs Foundation 4.78 g carbs / 0.942 g fiber (kcal absent); nutrients are never transferred.",
    conclusion: "Positive species/color/state/whole-form equivalence permits transfer of the whole-pepper size masses only; the RACC reference amount is not a household conversion and is never used.",
  },
  {
    record_key: "red bell pepper|item|small|null",
    source_fdc_id: 170108,
    source_description: "Peppers, sweet, red, raw",
    bound_fdc_id: 2258590,
    bound_description: "Peppers, bell, red, raw",
    species_family: "Capsicum annuum (bell/sweet pepper), red",
    state: "raw in both records",
    color_variety: "red; USDA uses \"sweet\" and \"bell\" for the same red pepper",
    edible_form: "whole pepper; the SR record also exposes strips/rings",
    positive_evidence: "The bound Foundation record \"Peppers, bell, red, raw\" and the SR record \"Peppers, sweet, red, raw\" name the same red pepper food: both are raw, both are red, and both describe the whole-pepper item.",
    corroborating_portion: "The bound Foundation record declares a RACC reference amount (85 g) and no household size class; the SR record supplies the authenticated small/medium/large item masses.",
    data_type_difference: "SR Legacy composition record vs Foundation modern analytical record for the same food.",
    nutrient_profile_delta: "Per-100-g: SR 26 kcal / 6.03 g carbs / 2.1 g fiber vs Foundation 6.65 g carbs / 1.16 g fiber; nutrients are never transferred.",
    conclusion: "Positive species/color/state/whole-form equivalence permits transfer of the whole-pepper size masses only; the RACC reference amount is never used.",
  },
  {
    record_key: "red bell pepper|item|medium|null",
    source_fdc_id: 170108,
    source_description: "Peppers, sweet, red, raw",
    bound_fdc_id: 2258590,
    bound_description: "Peppers, bell, red, raw",
    species_family: "Capsicum annuum (bell/sweet pepper), red",
    state: "raw in both records",
    color_variety: "red; USDA uses \"sweet\" and \"bell\" for the same red pepper",
    edible_form: "whole pepper; the SR record also exposes strips/rings",
    positive_evidence: "The bound Foundation record \"Peppers, bell, red, raw\" and the SR record \"Peppers, sweet, red, raw\" name the same red pepper food: both are raw, both are red, and both describe the whole-pepper item.",
    corroborating_portion: "The bound Foundation record declares a RACC reference amount (85 g) and no household size class; the SR record supplies the authenticated small/medium/large item masses.",
    data_type_difference: "SR Legacy composition record vs Foundation modern analytical record for the same food.",
    nutrient_profile_delta: "Per-100-g: SR 26 kcal / 6.03 g carbs / 2.1 g fiber vs Foundation 6.65 g carbs / 1.16 g fiber; nutrients are never transferred.",
    conclusion: "Positive species/color/state/whole-form equivalence permits transfer of the whole-pepper size masses only; the RACC reference amount is never used.",
  },
  {
    record_key: "red bell pepper|item|large|null",
    source_fdc_id: 170108,
    source_description: "Peppers, sweet, red, raw",
    bound_fdc_id: 2258590,
    bound_description: "Peppers, bell, red, raw",
    species_family: "Capsicum annuum (bell/sweet pepper), red",
    state: "raw in both records",
    color_variety: "red; USDA uses \"sweet\" and \"bell\" for the same red pepper",
    edible_form: "whole pepper; the SR record also exposes strips/rings",
    positive_evidence: "The bound Foundation record \"Peppers, bell, red, raw\" and the SR record \"Peppers, sweet, red, raw\" name the same red pepper food: both are raw, both are red, and both describe the whole-pepper item.",
    corroborating_portion: "The bound Foundation record declares a RACC reference amount (85 g) and no household size class; the SR record supplies the authenticated small/medium/large item masses.",
    data_type_difference: "SR Legacy composition record vs Foundation modern analytical record for the same food.",
    nutrient_profile_delta: "Per-100-g: SR 26 kcal / 6.03 g carbs / 2.1 g fiber vs Foundation 6.65 g carbs / 1.16 g fiber; nutrients are never transferred.",
    conclusion: "Positive species/color/state/whole-form equivalence permits transfer of the whole-pepper size masses only; the RACC reference amount is never used.",
  },
  {
    record_key: "green cabbage|head|small|null",
    source_fdc_id: 169975,
    source_description: "Cabbage, raw",
    bound_fdc_id: 2346407,
    bound_description: "Cabbage, green, raw",
    species_family: "Brassica oleracea var. capitata (common/green cabbage)",
    state: "raw in both records",
    color_variety: "green/common cabbage",
    edible_form: "whole head",
    positive_evidence: "The SR record \"Cabbage, raw\" is the common green cabbage and the bound Foundation record is explicitly \"Cabbage, green, raw\"; both are raw and both describe the head-forming cabbage.",
    corroborating_portion: "The bound Foundation record declares a RACC reference amount (85 g) and no household head-size class; the SR record supplies the authenticated small/medium/large head masses.",
    data_type_difference: "SR Legacy composition record vs Foundation modern analytical record for the same food.",
    nutrient_profile_delta: "Per-100-g: SR 25 kcal / 5.8 g carbs / 2.5 g fiber vs Foundation 6.38 g carbs / 0.228 g fat (kcal absent); nutrients are never transferred.",
    conclusion: "Positive species/color/state/head-form equivalence permits transfer of the head size masses only; the RACC reference amount is never used.",
  },
  {
    record_key: "green cabbage|head|medium|null",
    source_fdc_id: 169975,
    source_description: "Cabbage, raw",
    bound_fdc_id: 2346407,
    bound_description: "Cabbage, green, raw",
    species_family: "Brassica oleracea var. capitata (common/green cabbage)",
    state: "raw in both records",
    color_variety: "green/common cabbage",
    edible_form: "whole head",
    positive_evidence: "The SR record \"Cabbage, raw\" is the common green cabbage and the bound Foundation record is explicitly \"Cabbage, green, raw\"; both are raw and both describe the head-forming cabbage.",
    corroborating_portion: "The bound Foundation record declares a RACC reference amount (85 g) and no household head-size class; the SR record supplies the authenticated small/medium/large head masses.",
    data_type_difference: "SR Legacy composition record vs Foundation modern analytical record for the same food.",
    nutrient_profile_delta: "Per-100-g: SR 25 kcal / 5.8 g carbs / 2.5 g fiber vs Foundation 6.38 g carbs / 0.228 g fat (kcal absent); nutrients are never transferred.",
    conclusion: "Positive species/color/state/head-form equivalence permits transfer of the head size masses only; the RACC reference amount is never used.",
  },
  {
    record_key: "green cabbage|head|large|null",
    source_fdc_id: 169975,
    source_description: "Cabbage, raw",
    bound_fdc_id: 2346407,
    bound_description: "Cabbage, green, raw",
    species_family: "Brassica oleracea var. capitata (common/green cabbage)",
    state: "raw in both records",
    color_variety: "green/common cabbage",
    edible_form: "whole head",
    positive_evidence: "The SR record \"Cabbage, raw\" is the common green cabbage and the bound Foundation record is explicitly \"Cabbage, green, raw\"; both are raw and both describe the head-forming cabbage.",
    corroborating_portion: "The bound Foundation record declares a RACC reference amount (85 g) and no household head-size class; the SR record supplies the authenticated small/medium/large head masses.",
    data_type_difference: "SR Legacy composition record vs Foundation modern analytical record for the same food.",
    nutrient_profile_delta: "Per-100-g: SR 25 kcal / 5.8 g carbs / 2.5 g fiber vs Foundation 6.38 g carbs / 0.228 g fat (kcal absent); nutrients are never transferred.",
    conclusion: "Positive species/color/state/head-form equivalence permits transfer of the head size masses only; the RACC reference amount is never used.",
  },
  {
    record_key: "red cabbage|head|small|null",
    source_fdc_id: 169977,
    source_description: "Cabbage, red, raw",
    bound_fdc_id: 2346408,
    bound_description: "Cabbage, red, raw",
    species_family: "Brassica oleracea var. capitata (red cabbage)",
    state: "raw in both records",
    color_variety: "red",
    edible_form: "whole head",
    positive_evidence: "Both records carry the red cabbage identity (\"Cabbage, red, raw\" on each side), are raw, and describe the head-forming cabbage.",
    corroborating_portion: "The bound Foundation record declares a RACC reference amount (85 g) and no household head-size class; the SR record supplies the authenticated small/medium/large head masses.",
    data_type_difference: "SR Legacy composition record vs Foundation modern analytical record for the same food.",
    nutrient_profile_delta: "Per-100-g: SR 31 kcal / 7.37 g carbs / 2.1 g fiber vs Foundation 6.79 g carbs / 0.214 g fat; nutrients are never transferred.",
    conclusion: "Positive species/color/state/head-form equivalence permits transfer of the head size masses only; the RACC reference amount is never used.",
  },
  {
    record_key: "red cabbage|head|medium|null",
    source_fdc_id: 169977,
    source_description: "Cabbage, red, raw",
    bound_fdc_id: 2346408,
    bound_description: "Cabbage, red, raw",
    species_family: "Brassica oleracea var. capitata (red cabbage)",
    state: "raw in both records",
    color_variety: "red",
    edible_form: "whole head",
    positive_evidence: "Both records carry the red cabbage identity (\"Cabbage, red, raw\" on each side), are raw, and describe the head-forming cabbage.",
    corroborating_portion: "The bound Foundation record declares a RACC reference amount (85 g) and no household head-size class; the SR record supplies the authenticated small/medium/large head masses.",
    data_type_difference: "SR Legacy composition record vs Foundation modern analytical record for the same food.",
    nutrient_profile_delta: "Per-100-g: SR 31 kcal / 7.37 g carbs / 2.1 g fiber vs Foundation 6.79 g carbs / 0.214 g fat; nutrients are never transferred.",
    conclusion: "Positive species/color/state/head-form equivalence permits transfer of the head size masses only; the RACC reference amount is never used.",
  },
  {
    record_key: "red cabbage|head|large|null",
    source_fdc_id: 169977,
    source_description: "Cabbage, red, raw",
    bound_fdc_id: 2346408,
    bound_description: "Cabbage, red, raw",
    species_family: "Brassica oleracea var. capitata (red cabbage)",
    state: "raw in both records",
    color_variety: "red",
    edible_form: "whole head",
    positive_evidence: "Both records carry the red cabbage identity (\"Cabbage, red, raw\" on each side), are raw, and describe the head-forming cabbage.",
    corroborating_portion: "The bound Foundation record declares a RACC reference amount (85 g) and no household head-size class; the SR record supplies the authenticated small/medium/large head masses.",
    data_type_difference: "SR Legacy composition record vs Foundation modern analytical record for the same food.",
    nutrient_profile_delta: "Per-100-g: SR 31 kcal / 7.37 g carbs / 2.1 g fiber vs Foundation 6.79 g carbs / 0.214 g fat; nutrients are never transferred.",
    conclusion: "Positive species/color/state/head-form equivalence permits transfer of the head size masses only; the RACC reference amount is never used.",
  },
  {
    record_key: "unsalted butter|stick|null|null",
    source_fdc_id: 173430,
    source_description: "Butter, without salt",
    bound_fdc_id: 789828,
    bound_description: "Butter, stick, unsalted",
    species_family: "bovine milk fat (butter)",
    state: "finished dairy product; neither record declares a cooked/raw state",
    color_variety: "unsalted in both records",
    edible_form: "stick form: the bound description explicitly declares \"stick\"",
    positive_evidence: "Both records are the unsalted butter identity, and the bound Foundation description explicitly declares the stick form that the SR authenticated portion measures (\"stick\").",
    corroborating_portion: "SR 173430 declares \"stick\" = 113 g; the bound record declares no portions.",
    data_type_difference: "SR Legacy composition record vs Foundation modern analytical record for the same food.",
    nutrient_profile_delta: "Per-100-g: SR 717 kcal / 81.1 g fat / 11 mg sodium vs Foundation 81.5 g fat / 10 mg sodium (kcal absent); nutrients are never transferred.",
    conclusion: "Positive species/variety/form equivalence permits transfer of the stick mass relationship only; no nutrient authority transfers.",
  },
  {
    record_key: "white mushroom|item|small|null",
    source_fdc_id: 169251,
    source_description: "Mushrooms, white, raw",
    bound_fdc_id: 2709793,
    bound_description: "Mushrooms, raw",
    species_family: "Agaricus bisporus (white/button mushroom)",
    state: "raw in both records",
    color_variety: "white/button; the bound FNDDS record is the plain raw-mushroom identity",
    edible_form: "whole mushroom",
    positive_evidence: "Both records describe raw mushrooms, and the bound FNDDS record declares its own whole-mushroom portion (\"1 whole\") at exactly the SR medium whole value.",
    corroborating_portion: "FNDDS 2709793 \"1 whole\" reports 18 g (amount omitted) and equals SR 169251 \"medium\" = 18 g exactly.",
    data_type_difference: "SR Legacy composition record vs FNDDS survey-grouping record.",
    nutrient_profile_delta: "Per-100-g: SR 22 kcal / 3.26 g carbs / 1.0 g fiber vs FNDDS 31 kcal / 4.13 g carbs / 1.7 g fiber; nutrients are never transferred.",
    conclusion: "Positive species/state/whole-form equivalence plus an exact whole-item gram match permits transfer of the item size masses only.",
  },
  {
    record_key: "white mushroom|item|medium|null",
    source_fdc_id: 169251,
    source_description: "Mushrooms, white, raw",
    bound_fdc_id: 2709793,
    bound_description: "Mushrooms, raw",
    species_family: "Agaricus bisporus (white/button mushroom)",
    state: "raw in both records",
    color_variety: "white/button; the bound FNDDS record is the plain raw-mushroom identity",
    edible_form: "whole mushroom",
    positive_evidence: "Both records describe raw mushrooms, and the bound FNDDS record declares its own whole-mushroom portion (\"1 whole\") at exactly the SR medium whole value.",
    corroborating_portion: "FNDDS 2709793 \"1 whole\" reports 18 g (amount omitted) and equals SR 169251 \"medium\" = 18 g exactly.",
    data_type_difference: "SR Legacy composition record vs FNDDS survey-grouping record.",
    nutrient_profile_delta: "Per-100-g: SR 22 kcal / 3.26 g carbs / 1.0 g fiber vs FNDDS 31 kcal / 4.13 g carbs / 1.7 g fiber; nutrients are never transferred.",
    conclusion: "Positive species/state/whole-form equivalence plus an exact whole-item gram match permits transfer of the item size masses only.",
  },
  {
    record_key: "white mushroom|item|large|null",
    source_fdc_id: 169251,
    source_description: "Mushrooms, white, raw",
    bound_fdc_id: 2709793,
    bound_description: "Mushrooms, raw",
    species_family: "Agaricus bisporus (white/button mushroom)",
    state: "raw in both records",
    color_variety: "white/button; the bound FNDDS record is the plain raw-mushroom identity",
    edible_form: "whole mushroom",
    positive_evidence: "Both records describe raw mushrooms, and the bound FNDDS record declares its own whole-mushroom portion (\"1 whole\") at exactly the SR medium whole value.",
    corroborating_portion: "FNDDS 2709793 \"1 whole\" reports 18 g (amount omitted) and equals SR 169251 \"medium\" = 18 g exactly.",
    data_type_difference: "SR Legacy composition record vs FNDDS survey-grouping record.",
    nutrient_profile_delta: "Per-100-g: SR 22 kcal / 3.26 g carbs / 1.0 g fiber vs FNDDS 31 kcal / 4.13 g carbs / 1.7 g fiber; nutrients are never transferred.",
    conclusion: "Positive species/state/whole-form equivalence plus an exact whole-item gram match permits transfer of the item size masses only.",
  },
  {
    record_key: "peach|item|small|null",
    source_fdc_id: 169928,
    source_description: "Peaches, yellow, raw",
    bound_fdc_id: 2709249,
    bound_description: "Peach, raw",
    species_family: "Prunus persica (peach), yellow",
    state: "raw in both records",
    color_variety: "yellow peach; the bound FNDDS record is the plain raw-peach identity",
    edible_form: "whole fruit",
    positive_evidence: "Both records describe the raw peach, and the bound FNDDS record declares its own whole-fruit portion (\"1 fruit\") at exactly the SR medium whole value.",
    corroborating_portion: "FNDDS 2709249 \"1 fruit\" reports 150 g (amount omitted) and equals SR 169928 \"medium\" = 150 g exactly.",
    data_type_difference: "SR Legacy composition record vs FNDDS survey-grouping record.",
    nutrient_profile_delta: "Per-100-g: SR 39 kcal / 9.54 g carbs vs FNDDS 46 kcal / 10.1 g carbs; nutrients are never transferred.",
    conclusion: "Positive species/state/whole-form equivalence plus an exact whole-item gram match permits transfer of the item size masses only.",
  },
  {
    record_key: "peach|item|medium|null",
    source_fdc_id: 169928,
    source_description: "Peaches, yellow, raw",
    bound_fdc_id: 2709249,
    bound_description: "Peach, raw",
    species_family: "Prunus persica (peach), yellow",
    state: "raw in both records",
    color_variety: "yellow peach; the bound FNDDS record is the plain raw-peach identity",
    edible_form: "whole fruit",
    positive_evidence: "Both records describe the raw peach, and the bound FNDDS record declares its own whole-fruit portion (\"1 fruit\") at exactly the SR medium whole value.",
    corroborating_portion: "FNDDS 2709249 \"1 fruit\" reports 150 g (amount omitted) and equals SR 169928 \"medium\" = 150 g exactly.",
    data_type_difference: "SR Legacy composition record vs FNDDS survey-grouping record.",
    nutrient_profile_delta: "Per-100-g: SR 39 kcal / 9.54 g carbs vs FNDDS 46 kcal / 10.1 g carbs; nutrients are never transferred.",
    conclusion: "Positive species/state/whole-form equivalence plus an exact whole-item gram match permits transfer of the item size masses only.",
  },
  {
    record_key: "peach|item|large|null",
    source_fdc_id: 169928,
    source_description: "Peaches, yellow, raw",
    bound_fdc_id: 2709249,
    bound_description: "Peach, raw",
    species_family: "Prunus persica (peach), yellow",
    state: "raw in both records",
    color_variety: "yellow peach; the bound FNDDS record is the plain raw-peach identity",
    edible_form: "whole fruit",
    positive_evidence: "Both records describe the raw peach, and the bound FNDDS record declares its own whole-fruit portion (\"1 fruit\") at exactly the SR medium whole value.",
    corroborating_portion: "FNDDS 2709249 \"1 fruit\" reports 150 g (amount omitted) and equals SR 169928 \"medium\" = 150 g exactly.",
    data_type_difference: "SR Legacy composition record vs FNDDS survey-grouping record.",
    nutrient_profile_delta: "Per-100-g: SR 39 kcal / 9.54 g carbs vs FNDDS 46 kcal / 10.1 g carbs; nutrients are never transferred.",
    conclusion: "Positive species/state/whole-form equivalence plus an exact whole-item gram match permits transfer of the item size masses only.",
  },
].map((entry) => Object.freeze(entry as HouseholdPortionEquivalenceRationale)));

const DATASET: HouseholdInitialVerifiedDataset = Object.freeze({
  schema_version: HOUSEHOLD_PORTION_REGISTRY_SCHEMA_VERSION,
  registry_release: HOUSEHOLD_INITIAL_REGISTRY_RELEASE,
  source_bundle_release: HOUSEHOLD_INITIAL_SOURCE_BUNDLE_RELEASE,
  reviewed_at: HOUSEHOLD_INITIAL_REVIEWED_AT,
  record_count: RECORDS.length,
  registry_digest: HOUSEHOLD_INITIAL_REGISTRY_LOCK.registry_digest,
  provenance_digest: HOUSEHOLD_INITIAL_PROVENANCE_DIGEST,
  aggregate_release_digest: HOUSEHOLD_INITIAL_AGGREGATE_RELEASE_DIGEST,
  provenance: () => PROVENANCE,
  equivalence: () => EQUIVALENCE,
});

// ---------------------------------------------------------------------------
// Verified loader
// ---------------------------------------------------------------------------

/**
 * Loads the reviewed initial registry. Verifies the Phase 4 registry lock, the
 * provenance/equivalence contract, the fixed provenance digest, and the fixed
 * aggregate release digest; returns a fresh immutable registry plus the frozen
 * verified dataset, or a closed failure with no data exposed.
 */
export function loadHouseholdInitialRegistry(): HouseholdInitialLoadResult {
  const registryResult = loadHouseholdPortionRegistry(RECORDS, HOUSEHOLD_INITIAL_REGISTRY_LOCK);
  if (!registryResult.ok) return initialFailure('initial_registry_rejected');
  const registry = registryResult.registry;
  const records = registry.records();

  const input = {
    registryRelease: HOUSEHOLD_INITIAL_REGISTRY_RELEASE,
    records,
    provenance: PROVENANCE,
    equivalence: EQUIVALENCE,
  };
  const validation = validateHouseholdInitialProvenance(input);
  if (!validation.ok) return initialFailure('initial_provenance_invalid');

  let provenanceDigest: string;
  try {
    provenanceDigest = computeHouseholdInitialProvenanceDigest(input);
  } catch {
    return initialFailure('initial_provenance_invalid');
  }
  if (provenanceDigest !== HOUSEHOLD_INITIAL_PROVENANCE_DIGEST) {
    return initialFailure('initial_provenance_digest_mismatch');
  }

  const aggregateDigest = computeHouseholdInitialAggregateDigest({
    registryRelease: HOUSEHOLD_INITIAL_REGISTRY_RELEASE,
    recordCount: records.length,
    registryDigest: registry.metadata().registry_digest,
    provenanceDigest,
  });
  if (aggregateDigest !== HOUSEHOLD_INITIAL_AGGREGATE_RELEASE_DIGEST) {
    return initialFailure('initial_aggregate_digest_mismatch');
  }
  return { ok: true, registry, dataset: DATASET };
}
