/**
 * The Kitchen Codex — Create for Me modal (v0.7 Phase 2A).
 *
 * Explicit-invention UI. Flow: prompt + compact constraints -> Generate (draft
 * returned by the server, nothing saved) -> preview/edit a clearly-labeled
 * "Generated Draft / Not saved yet" -> explicit Save (via the existing recipe
 * write path). Generate NEVER saves, and the server NEVER returns a prompt or
 * any secret.
 */

import React, { useMemo, useReducer, useRef, useState } from 'react';
import { Sparkles, X, Loader2 } from 'lucide-react';
import type { NetworkAdapter } from '../application/adapters/NetworkAdapter';
import type { ObsidianRecipe } from '../types';
import type { GeneratedRecipeDraft, GeneratedRecipeProvenance } from '../schema/generatedRecipe';
import {
  requestGeneratedRecipe,
  CreateForMeConstraintsInput,
  parseEditedDraftLines,
  CreateRecipeClientError,
} from '../utils/createForMe';
import {
  generatedDraftToObsidianRecipe,
  GeneratedRecipePathCollisionError,
  GENERATED_RECIPE_COLLISION_MESSAGE,
} from '../application/createForMe';
import {
  createForMeReducer,
  initialCreateForMeState,
} from '../application/createForMeState';
import {
  createCreateForMeSession,
  runGuarded,
} from '../application/createForMeSession';

interface CreateForMeModalProps {
  isOpen: boolean;
  onClose: () => void;
  network: NetworkAdapter;
  onSaveRecipe: (recipe: ObsidianRecipe) => void | Promise<void>;
}

/** Presentational error state (exported for rendering tests). */
export function CreateForMeError({ message, onRetry, onClose }: { message: string; onRetry: () => void; onClose: () => void }) {
  return (
    <div className="space-y-3">
      <p className="text-sm text-white">{message}</p>
      <div className="flex gap-2">
        <button onClick={onRetry} className="px-3 py-1.5 rounded-lg text-xs font-medium bg-amber-500/10 text-amber-300 border border-amber-500/30">
          Try again
        </button>
        <button onClick={onClose} className="px-3 py-1.5 rounded-lg text-xs font-medium bg-white/10 text-gray-200 border border-white/10">
          Close
        </button>
      </div>
    </div>
  );
}

/** Presentational draft preview/editor (exported for rendering tests). */
export function CreateForMeDraftView({ draft, provenance }: { draft: GeneratedRecipeDraft; provenance: GeneratedRecipeProvenance }) {
  const ingredientsText = useMemo(() => {
    return draft.ingredients.map((i) => `${i.amount ?? ''} ${i.unit ?? ''} ${i.name}${i.preparation ? `, ${i.preparation}` : ''}`.trim()).join('\n');
  }, [draft]);
  const stepsText = useMemo(() => draft.steps.map((s) => s.text).join('\n'), [draft]);

  return (
    <div className="space-y-3">
      <div className="flex flex-wrap items-center gap-2">
        <span className="px-2 py-0.5 rounded-md text-[10px] font-semibold bg-violet-500/15 text-violet-300 border border-violet-500/40">Generated Draft</span>
        <span className="px-2 py-0.5 rounded-md text-[10px] font-semibold bg-amber-500/15 text-amber-300 border border-amber-500/40">Not saved yet</span>
        <span className="text-[10px] text-gray-500">AI-generated by {provenance.providerId}</span>
      </div>

      <label className="block text-xs text-gray-400">
        Title
        <input
          id="create-me-title"
          type="text"
          defaultValue={draft.title}
          className="mt-1 w-full px-3 py-1.5 text-xs bg-[#0C0C0C] border border-white/10 rounded-lg text-gray-200 focus:outline-none focus:border-amber-500/60"
        />
      </label>

      <label className="block text-xs text-gray-400">
        Ingredients (one per line)
        <textarea
          id="create-me-ingredients"
          defaultValue={ingredientsText}
          rows={Math.min(10, Math.max(4, draft.ingredients.length))}
          className="mt-1 w-full px-3 py-1.5 text-xs bg-[#0C0C0C] border border-white/10 rounded-lg text-gray-200 font-mono focus:outline-none focus:border-amber-500/60"
        />
      </label>

      <label className="block text-xs text-gray-400">
        Steps (one per line)
        <textarea
          id="create-me-steps"
          defaultValue={stepsText}
          rows={Math.min(10, Math.max(4, draft.steps.length))}
          className="mt-1 w-full px-3 py-1.5 text-xs bg-[#0C0C0C] border border-white/10 rounded-lg text-gray-200 font-mono focus:outline-none focus:border-amber-500/60"
        />
      </label>
    </div>
  );
}

export function CreateForMeModal({ isOpen, onClose, network, onSaveRecipe }: CreateForMeModalProps) {
  const [state, dispatch] = useReducer(createForMeReducer, initialCreateForMeState);
  const status = state.status;
  const error = state.error;
  const draft = state.draft;
  const provenance = state.provenance;
  const saving = state.saving;
  const [prompt, setPrompt] = useState('');
  const [servings, setServings] = useState('');
  const [maxTotalMinutes, setMaxTotalMinutes] = useState('');
  const [cuisine, setCuisine] = useState('');
  const [course, setCourse] = useState('');
  const [dietary, setDietary] = useState('');
  const [exclude, setExclude] = useState('');
  // Session liveness + re-entrancy guard: invalidates in-flight generation/save
  // results when the modal opens/closes/discards, and resets the local busy flag.
  const session = useRef(createCreateForMeSession());

  // Session boundary: any open/close transition advances the epoch (invalidating
  // in-flight results and clearing the busy guard) and resets to a clean state, so
  // a reopened modal starts fresh and a late completion from a closed session is
  // never dispatched.
  const prevOpen = useRef(isOpen);
  React.useEffect(() => {
    if (prevOpen.current !== isOpen) {
      prevOpen.current = isOpen;
      session.current.advance();
      dispatch({ type: 'CLOSE' });
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const constraints: CreateForMeConstraintsInput = {};
  const servingsNum = parseInt(servings, 10);
  if (!isNaN(servingsNum)) constraints.servings = servingsNum;
  const minsNum = parseInt(maxTotalMinutes, 10);
  if (!isNaN(minsNum)) constraints.maxTotalMinutes = minsNum;
  if (cuisine) constraints.cuisine = cuisine;
  if (course) constraints.course = course;
  if (dietary) constraints.dietary = dietary;
  if (exclude) constraints.excludeIngredients = exclude;

  const generate = async () => {
    if (!prompt.trim()) return;
    // A new generation attempt clears any stale error immediately.
    dispatch({ type: 'START_GENERATION' });
    await runGuarded(
      session.current,
      () => requestGeneratedRecipe(network, prompt, constraints),
      (result) => dispatch({ type: 'GENERATION_SUCCESS', draft: result.draft, provenance: result.provenance }),
      (err) => {
        const message =
          err instanceof CreateRecipeClientError && err.code === 'UNSUPPORTED_CAPABILITY'
            ? 'No configured AI provider supports recipe generation.'
            : "Couldn't generate a recipe right now.";
        dispatch({ type: 'GENERATION_FAILURE', message });
      }
    );
  };

  const save = async () => {
    if (!draft || !provenance) return;
    if (session.current.isBusy()) return; // reject a duplicate submission while saving
    session.current.setBusy(true);
    const id = (document.getElementById('create-me-title') as HTMLInputElement | null)?.value ?? draft.title;
    const ings = (document.getElementById('create-me-ingredients') as HTMLTextAreaElement | null)?.value ?? '';
    const steps = (document.getElementById('create-me-steps') as HTMLTextAreaElement | null)?.value ?? '';
    const edited = parseEditedDraftLines({ ...draft, title: id }, ings, steps);
    const recipe = generatedDraftToObsidianRecipe({ draft: edited, provenance });
    dispatch({ type: 'BEGIN_SAVE' });
    await runGuarded(
      session.current,
      async () => { await onSaveRecipe(recipe); },
      () => {
        session.current.setBusy(false);
        dispatch({ type: 'SAVE_SUCCESS' });
        onClose();
        setPrompt('');
      },
      (err) => {
        session.current.setBusy(false);
        // A save collision must never discard the draft — show a bounded message and
        // keep every edit so the user can rename and try again.
        const message =
          err instanceof GeneratedRecipePathCollisionError
            ? GENERATED_RECIPE_COLLISION_MESSAGE
            : "Couldn't save the recipe right now.";
        dispatch({ type: 'SAVE_COLLISION', message });
      }
    );
  };

  return (
    <div className="fixed inset-0 z-[70] flex items-center justify-center p-4 bg-black/70" role="dialog" aria-modal="true" aria-label="Create for Me">
      <div className="w-full max-w-2xl bg-[#0F0F0F] border border-white/10 rounded-2xl p-5 space-y-4 shadow-2xl max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between">
          <h2 className="flex items-center gap-2 font-serif font-bold text-base text-white">
            <Sparkles className="w-4 h-4 text-amber-400" />
            Create for Me
          </h2>
          <button onClick={() => { session.current.advance(); dispatch({ type: 'CLOSE' }); onClose(); }} aria-label="Close" className="text-gray-400 hover:text-white">
            <X className="w-4 h-4" />
          </button>
        </div>

        <p className="text-xs text-gray-400">
          Ask for an invented recipe with your own prompt and constraints. The result is a Generated
          Draft you can edit — nothing is saved to your vault until you press Save.
        </p>

        {status === 'error' ? (
          <CreateForMeError
            message={error}
            onRetry={() => { session.current.advance(); dispatch({ type: 'DISCARD' }); }}
            onClose={() => { session.current.advance(); dispatch({ type: 'CLOSE' }); onClose(); }}
          />
        ) : status === 'draft' && draft && provenance ? (
          <div className="space-y-3">
            <CreateForMeDraftView draft={draft} provenance={provenance} />
            {error && (
              <p className="text-xs text-rose-300 bg-rose-500/10 border border-rose-500/30 rounded-lg px-3 py-2">{error}</p>
            )}
            <div className="flex gap-2 pt-1">
              <button
                onClick={() => void save()}
                disabled={saving}
                className="px-3 py-1.5 rounded-lg text-xs font-bold bg-amber-500 hover:bg-amber-400 text-black disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
              >
                {saving && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
                {saving ? 'Saving…' : 'Save to Vault'}
              </button>
              <button onClick={() => { session.current.advance(); dispatch({ type: 'DISCARD' }); }} disabled={saving} className="px-3 py-1.5 rounded-lg text-xs font-medium bg-white/10 text-gray-200 border border-white/10">
                Discard
              </button>
            </div>
          </div>
        ) : (
          <div className="space-y-3">
            <label className="block text-xs text-gray-400">
              Prompt
              <textarea
                id="create-me-prompt"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Create a hearty chicken dinner with pantry staples, ready in about 30 minutes…"
                rows={4}
                className="mt-1 w-full px-3 py-1.5 text-xs bg-[#0C0C0C] border border-white/10 rounded-lg text-gray-200 placeholder-gray-500 focus:outline-none focus:border-amber-500/60"
              />
            </label>

            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              <input value={servings} onChange={(e) => setServings(e.target.value)} placeholder="Servings" className="px-3 py-1.5 text-xs bg-[#0C0C0C] border border-white/10 rounded-lg text-gray-200 placeholder-gray-500 focus:outline-none focus:border-amber-500/60" />
              <input value={maxTotalMinutes} onChange={(e) => setMaxTotalMinutes(e.target.value)} placeholder="Max time (min)" className="px-3 py-1.5 text-xs bg-[#0C0C0C] border border-white/10 rounded-lg text-gray-200 placeholder-gray-500 focus:outline-none focus:border-amber-500/60" />
              <input value={cuisine} onChange={(e) => setCuisine(e.target.value)} placeholder="Cuisine" className="px-3 py-1.5 text-xs bg-[#0C0C0C] border border-white/10 rounded-lg text-gray-200 placeholder-gray-500 focus:outline-none focus:border-amber-500/60" />
              <input value={course} onChange={(e) => setCourse(e.target.value)} placeholder="Course" className="px-3 py-1.5 text-xs bg-[#0C0C0C] border border-white/10 rounded-lg text-gray-200 placeholder-gray-500 focus:outline-none focus:border-amber-500/60" />
              <input value={dietary} onChange={(e) => setDietary(e.target.value)} placeholder="Dietary (comma sep.)" className="px-3 py-1.5 text-xs bg-[#0C0C0C] border border-white/10 rounded-lg text-gray-200 placeholder-gray-500 focus:outline-none focus:border-amber-500/60" />
              <input value={exclude} onChange={(e) => setExclude(e.target.value)} placeholder="Exclude ingredients" className="px-3 py-1.5 text-xs bg-[#0C0C0C] border border-white/10 rounded-lg text-gray-200 placeholder-gray-500 focus:outline-none focus:border-amber-500/60" />
            </div>

            <button
              onClick={() => void generate()}
              disabled={status === 'generating' || !prompt.trim()}
              className="px-3 py-1.5 rounded-lg text-xs font-bold bg-amber-500 hover:bg-amber-400 text-black disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
            >
              {status === 'generating' && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
              {status === 'generating' ? 'Generating recipe…' : 'Generate'}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

export default CreateForMeModal;
