import { describe, it, expect } from "vitest";
import { renderToString } from "react-dom/server";
import { CreateForMeModal, CreateForMeDraftView, CreateForMeError } from "../../src/components/CreateForMeModal.js";
import type { NetworkAdapter } from "../../src/application/adapters/NetworkAdapter.js";
import type { GeneratedRecipeDraft } from "../../src/schema/generatedRecipe.js";

function render(el: React.ReactElement): string {
  return renderToString(el);
}

const draft: GeneratedRecipeDraft = {
  title: "Lemon Chicken",
  ingredients: [{ name: "chicken" }, { name: "lemon" }],
  steps: [{ text: "Sear." }],
};

describe("Create for Me modal (v0.7 2A)", () => {
  it("initial state shows the prompt entry point and a Generate action, no key input", () => {
    const html = render(<CreateForMeModal isOpen network={{} as unknown as NetworkAdapter} onClose={() => {}} onSaveRecipe={async () => {}} />);
    expect(html).toContain("Create for Me");
    expect(html).toContain("Prompt");
    expect(html).toContain("Generate");
    // Constraint inputs exist, but NEVER a password/secret/key field.
    expect(html).not.toContain("type=\"password\"");
    expect(html).not.toContain("API key");
    expect(html).not.toContain("GEMINI_API_KEY");
    expect(html).not.toContain("Save key");
  });

  it("renders the draft preview with Generated Draft / Not saved yet labels and editable fields", () => {
    const html = render(<CreateForMeDraftView draft={draft} provenance={{ generated: true, providerId: "gemini", model: "gemini-test" }} />);
    expect(html).toContain("Generated Draft");
    expect(html).toContain("Not saved yet");
    expect(html).toContain("AI-generated by");
    expect(html).toContain("gemini");
    expect(html).toContain("Lemon Chicken");
    expect(html).toContain("chicken");
    // Editable title + ingredient/step textareas, no secret inputs.
    expect(html).toContain("create-me-title");
    expect(html).toContain("create-me-ingredients");
    expect(html).toContain("create-me-steps");
    expect(html).not.toContain("type=\"password\"");
    expect(html).not.toContain("API key");
  });

  it("does not render a fake source URL or prompt in the draft view", () => {
    const html = render(<CreateForMeDraftView draft={draft} provenance={{ generated: true, providerId: "gemini", model: "g" }} />);
    expect(html).not.toContain("source: http");
    expect(html).not.toContain("SUPER_SECRET_CREATE_PROMPT_SENTINEL");
    expect(html).not.toContain("[[");
  });

  it("renders a generic bounded error message in the error state", () => {
    const html = render(<CreateForMeError message="Couldn't generate a recipe right now." onRetry={() => {}} onClose={() => {}} />);
    expect(html).toContain("generate a recipe right now");
    expect(html).not.toContain("gemini-api-key");
    expect(html).not.toContain("Bearer");
  });

  it("renders the generating state text while a request is in flight", () => {
    const html = render(<CreateForMeModal isOpen network={{} as unknown as NetworkAdapter} onClose={() => {}} onSaveRecipe={async () => {}} />);
    // The prompt step has no "Generating" yet; the Generate button label is present.
    expect(html).toContain("Generate");
  });
});
